#!/bin/bash

PLAYERCTL_STATUS=$(playerctl status 2>/dev/null)
EXIT_CODE=$?
if [ $EXIT_CODE -eq 0 ]; then
    STATUS=$PLAYERCTL_STATUS
    icon="󰏥"
    if [ $STATUS == "Paused" -o $STATUS == "Stopped" ]; then
      icon="󰐌"
    fi
    SONG_NAME=$(playerctl metadata title 2>/dev/null)
    ARTIST_NAME=$(playerctl metadata artist 2>/dev/null)
    POSITION=$(playerctl position)
    LENGTH=$(playerctl metadata mpris:length)
    LENGTH=$((LENGTH / 1000))
else
    STATUS=""
    SONG_NAME="Audio player"
    ARTIST_NAME="None active"
    icon="󰐌"
    POSITION=0
    LENGTH=100
fi


if [[ $1 == "--status" ]]; then
    echo $STATUS
elif [[ $1 == "--song" ]]; then
  count=$(echo -n "$SONG_NAME" | wc -c)
  if [ "$count" -le 17 ]; then
		echo $SONG_NAME
	else 
		echo ${SONG_NAME:0:17}...
	fi
elif [[ $1 == "--artist" ]]; then
    echo $ARTIST_NAME
elif [[ $1 == "--image" ]]; then
    echo $IMAGE
elif [[ $1 == "--icon" ]]; then
    echo $icon
elif [[ $1 == "--pos" ]]; then
    echo $POSITION
elif [[ $1 == "--len" ]]; then
    echo $LENGTH
elif [[ $1 == "--loop" ]]; then
    echo $LOOP
elif [[ $1 == "--shuf" ]]; then
    echo $SHUFFLE
fi
