#!/bin/bash

declare -A substitutes

if [[ $HOSTNAME == "otm" ]]; then
  if [[ $1 == "starship" ]]; then
    substitutes[host_symbol]="♞"
    substitutes[host_accent]="#9A348E"
  elif [[ $1 == "fish" ]]; then
    substitutes[greeting]="neofetch"
  elif [[ $1 == "kitty" ]]; then
    substitutes[overrides_file]="overrides.conf"
  fi

elif [[ $HOSTNAME == "homeserver" ]]; then
  if [[ $1 == "starship" ]]; then
    substitutes[host_symbol]="♚"
    substitutes[host_accent]="#AA2C5C"
  elif [[ $1 == "fish" ]]; then
    substitutes[greeting]="figlet -w 120 -f broadway vhut"
  elif [[ $1 == "kitty" ]]; then
    substitutes[overrides_file]="overrides.conf"
  fi

elif [[ "$HOSTNAME" =~ "MacBook.*" ]]; then
  if [[ $1 == "kitty" ]]; then
    substitutes[overrides_file]="mac-overrides.conf"
  fi

else 
  if [[ $1 == "starship" ]]; then
    substitutes[host_symbol]="♟"
    substitutes[host_accent]="#4A32AA"
  elif [[ $1 == "fish" ]]; then
    substitutes[greeting]="neofetch"
  elif [[ $1 == "kitty" ]]; then
    substitutes[overrides_file]="overrides.conf"
  fi
fi
