#!/bin/bash

current="$HOME/repos/dotconfig/src"
cd $current

declare -A targets

targets[nvim]=".config/nvim/"
targets[tmux]=".config/tmux"
targets[nushell]=".config/nushell"
targets[rofi]=".config/rofi"
targets[eww]=".config/eww"
targets[omp]=".oh-my-posh.nu"
targets[vim]=".vimrc"
targets[bash]=".bashrc"
targets[kitty]=".config/kitty"
targets[zathura]=".config/zathura"
targets[neomutt]=".config/neomutt"
targets[arduino]=".arduino15"
targets[yazi]=".config/yazi"
targets[spotify-tui]=".config/spotify-tui"
targets[dunst]=".config/dunst"
targets[hypr]=".config/hypr"
targets[ags]=".config/ags"
targets[swaylock]=".config/swaylock"
targets[kanata]=".config/kanata"

echo "============================== Deploying dots =============================="

for t in "${targets[@]}"; do
  # If the target is a directory
  if [[ -d $t ]]; then 
    if [[ ! -d $HOME/$t ]]; then 
      printf "Initializing %50s\n" "$HOME/$t"
      mkdir -p $HOME/$t
    fi
    cp -rf $current/$t/* $HOME/$t

  # If the target is a file
  elif [[ -f $t ]]; then 
    cp $current/$t $HOME
  fi

  printf "$t %50s\n" " ==> $HOME/$t" 
done

echo "================================= All done ================================="
