[manager]
prepend_keymap = [
  { on = ["<C-h>"], run = 'hidden toggle' },
  { on = ["<S-Enter>"], run = 'open --interactive'},
  { on = [ "y" ], run = [ "yank", '''shell --confirm 'cat $(echo $@) | wl-copy'''' ]}
]


