[opener]
edit = [
  { run = 'kitten @ launch --type=tab nvim "$@"' }
]

open = [
  { run = 'xdg-open "$@"', orphan = true }
]

img = [
  { run = 'imv "$@"', orphan = true }
]

imgedit = [
  { run = 'gimp "$@"', orphan = true }
]

svg = [
  { run = 'inkscape $@', orphan = true }
]

[open]
rules = [
	{ mime = "text/*",                  use = [ "edit" ] },

	{ mime = "image/*", name = "*.svg", use = [ "svg" ] },
	{ mime = "image/*",                 use = [ "img", "imgedit", "open" ] },

	{ mime = "audio/*",                 use = [ "img", "imgedit", "open" ] },

  { mime = "*", use = [ "open" ] }
]

[plugin]
prepend_previewers  = [
  { mime = "image/svg", run = "image" }
]

