#!/bin/bash

arg1=$1
shift
args="$*"

min=${arg1:?Example: pomo 15 Take a break}
sec=$((min * 60))
msg="${args:?Example: pomo 15 Take a break}"

notify-send -u normal -a Pomodoro "Focusing for ${min}m 🍅"

sleep "${sec:?}" && notify-send -u normal -a Pomodoro "${msg:?} 🍅"
